### Ejercicios Clase 9
#### 1. Crear una matriz de ceros de tipo entero 3x4

In [2]:
import numpy as np

In [8]:
matriz = np.zeros((3,4),int)
print(matriz)
type(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

#### 2. Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno


In [12]:
matriz = np.zeros((3,4),int)
unos = np.ones(4)
matriz[0] = unos
print(matriz)

[[1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]


#### 3. Crear una matriz de ceros de tipo entero 3x4 excepto la última fila que será el rango entre 5 y 8


In [22]:
matriz = np.zeros((2,4),int)
rango = np.arange(5,9,dtype=int)
matriz = np.vstack([matriz,rango])
print(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [5 6 7 8]]


#### 4. Crea un vector de 10 elementos, siendo los índices impares unos y los índices pares dos


In [45]:
vector = np.arange(0,11,dtype=int) 
vector[vector%2==0] = 2
vector[vector%2==1] = 1
vector 

array([2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])