### Ejercicios Clase 9
#### 1. Crear una matriz de ceros de tipo entero 3x4

In [2]:
import numpy as np

In [8]:
matriz = np.zeros((3,4),int)
print(matriz)
type(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

#### 2. Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno


In [12]:
matriz = np.zeros((3,4),int)
unos = np.ones(4)
matriz[0] = unos
print(matriz)

[[1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]


#### 3. Crear una matriz de ceros de tipo entero 3x4 excepto la última fila que será el rango entre 5 y 8


In [22]:
matriz = np.zeros((2,4),int)
rango = np.arange(5,9,dtype=int)
matriz = np.vstack([matriz,rango])
print(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [5 6 7 8]]


#### 4. Crea un vector de 10 elementos, siendo los índices impares unos y los índices pares dos


In [50]:
#Forma 1
vector = np.arange(0,10,dtype=int) 
vector[vector%2==0] = 2
vector[vector%2==1] = 1
print(vector)

[2 1 2 1 2 1 2 1 2 1]


In [ ]:
#Forma 2
vector = np.zeros(10, dtype=int)
vector[::2] = 2  # Índices pares: 0, 2, 4, ...
vector[1::2] = 1  # Índices impares: 1, 3, 5, ...
print(vector)
type(vector)


[2 1 2 1 2 1 2 1 2 1]


numpy.ndarray

#### 5. Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas


In [ ]:
#Forma 1
fila = np.arange(8,dtype=int)
fila[fila%2 == 1] = 1
tablero = np.zeros((8,8),int)
for i in range(8):
    if i%2==0:
        tablero[i] = fila
    else:
        tablero[i] = fila[::-1]
tablero[tablero!=1] = 0

print(tablero)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [82]:
#Forma 2
tablero = np.zeros((8, 8), dtype=int)
tablero[1::2, ::2] = 1  # Filas impares, columnas pares
tablero[::2, 1::2] = 1  # Filas pares, columnas impares

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 6. Crea una matriz aleatoria 5x5 y halla los valores mínimo y máximo

In [102]:
matrizAleatoria = np.random.randint(0,100,(5,5))
maximo = np.max(matrizAleatoria)
minimo = np.min(matrizAleatoria)
print(matrizAleatoria)
print(f"Máximo: {maximo}")
print(f"Mínimo: {minimo}")

[[10 15  5 52 66]
 [41 33 96 24 77]
 [65 79 43 95 96]
 [91 11 59 22 97]
 [68 47 65 88  1]]
Máximo: 97
Mínimo: 1


#### 7. Normalizar la matriz anterior

In [129]:
magnitud = np.sum(np.power(matrizAleatoria,2))
magnitud = np.power(magnitud,1/2)
print(magnitud)
matrizNormal = matrizAleatoria/magnitud
print(matrizNormal)

6.5030445793797105
[[0.19103346 0.13190406 0.07277465 0.09096831 0.09551673]
 [0.32748593 0.05003257 0.18648505 0.38661534 0.19558188]
 [0.30474385 0.32293752 0.1728398  0.09551673 0.11825881]
 [0.15464614 0.32748593 0.01364525 0.1728398  0.16374297]
 [0.30474385 0.02729049 0.20922712 0.12280722 0.02274208]]
