### Ejercicios Clase 9
#### 1. Crear una matriz de ceros de tipo entero 3x4

In [2]:
import numpy as np

In [8]:
matriz = np.zeros((3,4),int)
print(matriz)
type(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

#### 2. Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno


In [12]:
matriz = np.zeros((3,4),int)
unos = np.ones(4)
matriz[0] = unos
print(matriz)

[[1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]


#### 3. Crear una matriz de ceros de tipo entero 3x4 excepto la última fila que será el rango entre 5 y 8


In [22]:
matriz = np.zeros((2,4),int)
rango = np.arange(5,9,dtype=int)
matriz = np.vstack([matriz,rango])
print(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [5 6 7 8]]


#### 4. Crea un vector de 10 elementos, siendo los índices impares unos y los índices pares dos


In [50]:
#Forma 1
vector = np.arange(0,10,dtype=int) 
vector[vector%2==0] = 2
vector[vector%2==1] = 1
print(vector)

[2 1 2 1 2 1 2 1 2 1]


In [ ]:
#Forma 2
vector = np.zeros(10, dtype=int)
vector[::2] = 2  # Índices pares: 0, 2, 4, ...
vector[1::2] = 1  # Índices impares: 1, 3, 5, ...
print(vector)
type(vector)


[2 1 2 1 2 1 2 1 2 1]


numpy.ndarray

#### 5. Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas


In [ ]:
#Forma 1
fila = np.arange(8,dtype=int)
fila[fila%2 == 1] = 1
tablero = np.zeros((8,8),int)
for i in range(8):
    if i%2==0:
        tablero[i] = fila
    else:
        tablero[i] = fila[::-1]
tablero[tablero!=1] = 0

print(tablero)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [82]:
#Forma 2
tablero = np.zeros((8, 8), dtype=int)
tablero[1::2, ::2] = 1  # Filas impares, columnas pares
tablero[::2, 1::2] = 1  # Filas pares, columnas impares

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 6. Crea una matriz aleatoria 5x5 y halla los valores mínimo y máximo

In [100]:
matriz = np.random.randint(0,100,(5,5))
maximo = np.max(matriz)
minimo = np.min(matriz)
print(matriz)
print(f"Máximo: {maximo}")
print(f"Mínimo: {minimo}")

[[40 89  6 13 69]
 [59 55 92 56 36]
 [23 24 73 66 32]
 [13  1  3 31 92]
 [72 58  1 88 51]]
Máximo: 92
Mínimo: 1
