### Ejercicios Clase 9
#### Crear una matriz de ceros de tipo entero 3x4

In [2]:
import numpy as np

In [8]:
matriz = np.zeros((3,4),int)
print(matriz)
type(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

#### Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno


In [ ]:
matriz = np.zeros((3,4),int)
unos = np.ones(4)
matriz[0] = uno

SyntaxError: invalid syntax (150758373.py, line 3)