### Ejercicios Clase 9
#### 1. Crear una matriz de ceros de tipo entero 3x4

In [2]:
import numpy as np

In [8]:
matriz = np.zeros((3,4),int)
print(matriz)
type(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray

#### 2. Crear una matriz de ceros de tipo entero 3x4 excepto la primera fila que será uno


In [12]:
matriz = np.zeros((3,4),int)
unos = np.ones(4)
matriz[0] = unos
print(matriz)

[[1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]


#### 3. Crear una matriz de ceros de tipo entero 3x4 excepto la última fila que será el rango entre 5 y 8


In [22]:
matriz = np.zeros((2,4),int)
rango = np.arange(5,9,dtype=int)
matriz = np.vstack([matriz,rango])
print(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [5 6 7 8]]


#### 4. Crea un vector de 10 elementos, siendo los índices impares unos y los índices pares dos


In [50]:
#Forma 1
vector = np.arange(0,10,dtype=int) 
vector[vector%2==0] = 2
vector[vector%2==1] = 1
print(vector)

[2 1 2 1 2 1 2 1 2 1]


In [ ]:
#Forma 2
vector = np.zeros(10, dtype=int)
vector[::2] = 2  # Índices pares: 0, 2, 4, ...
vector[1::2] = 1  # Índices impares: 1, 3, 5, ...
print(vector)
type(vector)


[2 1 2 1 2 1 2 1 2 1]


numpy.ndarray

#### 5. Crea un «tablero de ajedrez», con unos en las casillas negras y ceros en las blancas


In [ ]:
#Forma 1
fila = np.arange(8,dtype=int)
fila[fila%2 == 1] = 1
tablero = np.zeros((8,8),int)
for i in range(8):
    if i%2==0:
        tablero[i] = fila
    else:
        tablero[i] = fila[::-1]
tablero[tablero!=1] = 0

print(tablero)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [82]:
#Forma 2
tablero = np.zeros((8, 8), dtype=int)
tablero[1::2, ::2] = 1  # Filas impares, columnas pares
tablero[::2, 1::2] = 1  # Filas pares, columnas impares

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 6. Crea una matriz aleatoria 5x5 y halla los valores mínimo y máximo

In [131]:
matrizAleatoria = np.random.randint(0,100,(5,5))
maximo = np.max(matrizAleatoria)
minimo = np.min(matrizAleatoria)
print(matrizAleatoria)
print(f"Máximo: {maximo}")
print(f"Mínimo: {minimo}")

[[ 2 90 81 30 91]
 [83 85 19 14 77]
 [32 31 61 96 47]
 [42 85 11 62 53]
 [27 27 39 42 55]]
Máximo: 96
Mínimo: 2


#### 7. Normalizar la matriz anterior

In [132]:
magnitud = np.sum(np.power(matrizAleatoria,2))
magnitud = np.power(magnitud,1/2)
print(magnitud)
matrizNormal = matrizAleatoria/magnitud
print(matrizNormal)

291.73275441746335
[[0.00685559 0.30850153 0.27765137 0.10283384 0.31192932]
 [0.28450696 0.29136255 0.0651281  0.04798913 0.26394019]
 [0.10968943 0.10626164 0.20909548 0.32906829 0.16110635]
 [0.14396738 0.29136255 0.03770574 0.21252327 0.18167312]
 [0.09255046 0.09255046 0.13368399 0.14396738 0.18852871]]
