### Ejercicios Clase 9
#### Crear una matriz de ceros de tipo entero 3x4

In [2]:
import numpy as np

In [8]:
matriz = np.zeros((3,4),int)
print(matriz)
type(matriz)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


numpy.ndarray